apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.apiGateway.replicaCount }}

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: {{ .Values.apiGateway.image }}
          imagePullPolicy: {{ .Values.apiGateway.imagePullPolicy }}

          ports:
            - containerPort: {{ .Values.apiGateway.servicePort }}