apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: frontend

  ports:
    - protocol: TCP
      port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}

  type: {{ .Values.frontend.serviceType }}