apiVersion: apps/v1
kind: Deployment

metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.mongodb.replicaCount }}

  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.mongodb.service.targetPort }}

          volumeMounts:
            - name: mongodb-storage
              mountPath: {{ .Values.mongodb.mountPath }}

      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc