apiVersion: v1
kind: Service

metadata:
  name: product-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: product-service

  ports:
    - protocol: TCP
      port: {{ .Values.productService.servicePort }}
      targetPort: {{ .Values.productService.servicePort }}

  type: {{ .Values.productService.serviceType }}