namespace: production-platform

frontend:
  replicaCount: 1
  image: nishayaduvanshi/frontend:2.1
  imagePullPolicy: IfNotPresent

  serviceType: NodePort
  servicePort: 80

apiGateway:
  replicaCount: 1
  image: nishayaduvanshi/api-gateway:2.1
  imagePullPolicy: IfNotPresent

  serviceType: ClusterIP
  servicePort: 3000

userService:
  replicaCount: 1
  image: nishayaduvanshi/user-service:1.0
  imagePullPolicy: IfNotPresent
  serviceType: ClusterIP
  servicePort: 3001

productService:
  replicaCount: 1
  image: nishayaduvanshi/product-service:1.0
  imagePullPolicy: IfNotPresent
  serviceType: ClusterIP
  servicePort: 3002

orderService:
  replicaCount: 1
  image: nishayaduvanshi/order-service:1.0
  imagePullPolicy: IfNotPresent
  serviceType: ClusterIP
  servicePort: 3003

mongodb:
  replicaCount: 1

  image:
    repository: mongo
    tag: "8"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 27017
    targetPort: 27017

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""

  mountPath: /data/db

ingress:
  enabled: true
  className: nginx
  host: ""

config:
  mongoUri: mongodb://mongodb:27017/devopsdb

secret:
  jwtSecret: devops-super-secret-key